### ISSUE TITLE
Improve List Scrolling

### ISSUE THREAD

**Issue by spipau** [ICT4Dat/ict4dat-news-android#159]
Use [this lib](https://github.com/timusus/RecyclerView-FastScroll) to improve the scroll bars in the News list. Use the a good fitting date format like: `"MMM yyyy"`.

**Comment by rajasone** [comment]
sure, looks good, actually i was going to ask you about this, since I saw a picture which you sent over group I was curious whether you wrote this functionality or using some library :)

**Comment by spipau** [comment]
I think this is the first third party lib I use 😄 
I guess I was too lazy and these kind of things are OK to be handled by a third party library? Or do you disagree and would like to implement it by yourself?

**Comment by rajasone** [comment]
@spipau Yes you are right, I think it's perfectly fine to use this library, I am not really motivated to write recycler view decoration code :rofl:
