### ISSUE TITLE
Update app images on Google play app page

### ISSUE THREAD

**Issue by jobguitiche** [ICT4Dat/ict4dat-news-android#224]
![2023-10-02_22h22_08](https://github.com/ICT4Dat/ict4dat-news-android/assets/10657415/aed40a3b-6930-4723-a5d5-780e7602370b)

**Comment by spipau** [comment]
I'd say that I'll take this ticket as I am the only one with access :)

**Comment by jobguitiche** [comment]
> I'd say that I'll take this ticket as I am the only one with access to the Play Console 🙂

I agree!

**Comment by spipau** [comment]
https://codeberg.org/ICT4Dat/ict4dat-news-android/issues/9
