### ISSUE TITLE
Create the ICT4D.at Fragment Layout

### ISSUE THREAD

**Issue by spipau** [ICT4Dat/ict4dat-news-android#31]
Implement the Layout for the `ICT4DatFragment` called `fragment_ict4dat`. You find in the Wiki a Link to the Wireframes. Use dummy text and images for now.

**Comment by jguitiche** [comment]
Hi,

It seems this link does not work any more

(https://gallery.io/projects/MCHbtQVoQ2HCZU6dARF5mTBQ)

**Comment by spipau** [comment]
Hi, check out the link in the [Wiki](https://github.com/ICT4Dat/ict4dat-news-android/wiki)

**Comment by jguitiche** [comment]
Hi,

On this link (https://github.com/ICT4Dat/ict4dat-news-android/wiki) the link in the words "can be found here" still not working. When I try to open, for now only a white page is showed.

**Comment by jguitiche** [comment]
Yeah... its working fine on Google Chrome. Now I can finish my issue :)
It is sad that chrome are implementing a kind of dictatorship on us.

**Comment by spipau** [comment]
Hi, do you still work on this issue? Because we have now a deadline and have to move fast ;) Write us when you find the time
