### ISSUE TITLE
Move to paging library android

### ISSUE THREAD

**Issue by rajasone** [ICT4Dat/ict4dat-news-android#60]
Move to paging library android if it feasible

**Comment by rajasone** [comment]
`compositeDisposable.add(Flowables.combineLatest(
persistenceManager.getAllActiveNewsAsFlowable(), persistenceManager.getAllActiveBlogsAsFlowable()) `

@spipau In `ICT4DNewsViewModel` we are fetching data from multiple sources and combine them into one `List` as mentioned above, I think creating two `DataSource.Factory` is not a clean solution for our scenario.

**Comment by spipau** [comment]
I have a solution (I think) and will take care of this issue
