### ISSUE TITLE
Create more and setting screen

### ISSUE THREAD

**Issue by rajasone** [ICT4Dat/ict4dat-news-android#66]
create more and setting screen follow the design here 
`https://gallery.io/projects/MCHbtQVoQ2HCZU6dARF5mTBQ/files/MCHtA7U1iMGr6-IZDBoZkdRlkRjI-sGGZ_Y`

**Comment by spipau** [comment]
Put the developer information of the developers in a String XML to make it better maintainable.

**Comment by noahalorwu** [comment]
I need your information @rajasone @spipau @jguitiche

**Comment by spipau** [comment]
How can I help you? 😉

**Comment by spipau** [comment]
Information:

Name: Paul Spiesberger
Description: Chairman of [ICT4D.at](http://www.ict4d.at/) - Android/iOS developer [Os](http://www.flaming-os.at/) and [RISE](https://www.rise-world.com/) - Researcher at [INSO](https://www.inso.tuwien.ac.at) - dedicated to social participation, individual freedom and empowerment.
Picture: will come soon 😉  - Use a dummy in the meanwhile

Please make the Links clickable in the text, thanks!

**Comment by noahalorwu** [comment]
Thanks for your profile info @spipau

**Comment by noahalorwu** [comment]
I will make the links clickable
